on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: Release policy

jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@b247e2a7dc4e14851d430b8f977272739d9d1692

  release:
    needs: test
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-go.yml@b247e2a7dc4e14851d430b8f977272739d9d1692
    with:
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/policy-name #FIXME
