on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: fabriziosestito/github-actions/.github/workflows/reusable-test-policy-go.yml@7810a1a3e2e75d59cf5f244849f27867fec2ccd1
