on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: fabriziosestito/github-actions/.github/workflows/reusable-test-policy-go.yml@c1ce2668b71cc514874e4a58090f28f0af1c146b
